version: 0.1

phases:
    install:
        commands:
            - apt-get -y update
            - apt-get -y install zip
            - npm install -g serverless@1.9.0

    build:
        commands:
            - ./build.sh
  
artifacts:
    files:
         - serverless.yml
         - publish.zip
         - promotion.sh
    discard-paths: yes