version: 0.2

phases:
    install:
        runtime: 
            dotnet: 2.2
        commands:
            - dotnet build
            - dotnet test
            - npm install -g serverless
    build:
        runtime:
            dotnet: 2.2
        commands:
            - dotnet publish -c release
    post_build:
        commands:
            - SLS_DEBUG=1 serverless deploy --stage dev --verbose
  
