version: 0.1

phases:
    install:
        commands:
            - apt-get -y update
            - apt-get -y install zip
            - npm install -g serverless@1.9.0

    build:
        commands:
            - ./build.sh
  
    post_build:
        commands:
            - sls deploy -v -s $STAGE
